ClearRTError: Return the error value
We can tweak ClearRTError() so that it can be used as drop-in
replacement for getRTError(1) by returning the error.

We also remove the DEBUGPRINT_TS statement as it floods the history.